---
repo_base: "https://mirrors.ustc.edu.cn"
debian_codename: "buster"
debian_repo:
  - "deb {{ repo_base }}/debian {{ debian_codename }} main contrib non-free"
  - "deb-src {{ repo_base }}/debian {{ debian_codename }} main contrib non-free"
  - "deb {{ repo_base }}/debian {{ debian_codename }}-backports main contrib non-free"
  - "deb-src {{ repo_base }}/debian {{ debian_codename }}-backports main contrib non-free"

common_packages:
  - htop
  - bash-completion
  - efibootmgr
  - network-manager
  - pavucontrol
  - plymouth
  - xorg
  - lightdm
  - lightdm-gtk-greeter
  - lxterminal
  - xfce4
  - alsa-utils
  - git
  - dialog
  - cmake
  - cryptsetup
  - gnupg
  - xz-utils
  - intel-microcode
  - rsync
  - wget
  - curl
  - mousepad
  - keepassxc
  - unrar
  - unzip
  - tcpdump
centos8:
ubuntu2004:
  fullupgrade: False
debian10:
  - aptitude
  - python3-pip
  - build-essential
  - firefox-esr
  - fonts-noto-cjk
  - fonts-noto-core
  - fcitx
  - fcitx-config-gtk
  - fcitx-frontend-gtk2
  - fcitx-frontend-gtk3
  - fcitx-frontend-qt5
  - fcitx-module-x11
  - fcitx-table
  - fcitx-table-wbpy
  - fcitx-ui-light
  - firmware-linux
  - firmware-linux-free
  - firmware-linux-nonfree
  - firmware-iwlwifi
